// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFJwVZ7uODie-T8dJtBBPspEVPvXe2MC4',
    appId: '1:239036246524:web:a58b3a1acb33ea61b1aa79',
    messagingSenderId: '239036246524',
    projectId: 'debate-tournament-management',
    authDomain: 'debate-tournament-management.firebaseapp.com',
    storageBucket: 'debate-tournament-management.firebasestorage.app',
    measurementId: 'G-G7KSZ9S3XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgCM_RhGuKWM4TStcvZd6U3WhXVoUWbYU',
    appId: '1:239036246524:android:64c618d829ac72d3b1aa79',
    messagingSenderId: '239036246524',
    projectId: 'debate-tournament-management',
    storageBucket: 'debate-tournament-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4pGsUSt-vGL31b-ZUCcHkm7QQnecrVQM',
    appId: '1:239036246524:ios:b3cfb3c2140d4508b1aa79',
    messagingSenderId: '239036246524',
    projectId: 'debate-tournament-management',
    storageBucket: 'debate-tournament-management.firebasestorage.app',
    iosBundleId: 'co',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFJwVZ7uODie-T8dJtBBPspEVPvXe2MC4',
    appId: '1:239036246524:web:67e7b4425af4176eb1aa79',
    messagingSenderId: '239036246524',
    projectId: 'debate-tournament-management',
    authDomain: 'debate-tournament-management.firebaseapp.com',
    storageBucket: 'debate-tournament-management.firebasestorage.app',
    measurementId: 'G-XHCL6Y9CV1',
  );
}
